spring:
  application:
    name: quiz-service


  datasource:
    url: jdbc:mysql://localhost:3306/quizdb
    username: root
    password: Saurabh@15

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      driver-class-name: com.mysql.cj.jdbc.Driver
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
   
   
   
server:
  port: 8004
  
  logging:
  level:
    org.apache.coyote: DEBUG