spring:
  application:
    name: service-registry

server:
  port: 8761  # Default port for Eureka

eureka:
  instance:
    hostname: localhost
    nonSecurePort: 8761
  client:
    fetch-registry: false
    register-with-eureka: false
  server:
    enableSelfPreservation: false  # Optional
